package com.infospace.sdk.models.actions;

import android.app.Application;
import android.content.*;
import android.widget.Toast;

/**
 * A class used to launch intents in conjunction with ResultActionProvider and IntentActionProvider.
 * <p/>
 * To add functionality to launch implicit intents using data generated by an IntentActionProvider, add the following code in Application.onCreate():
 * <pre>
 * AndroidActivityStarter implicitActivityStarter = new AndroidActivityStarter(applicationContext);
 * ResultActionProvider.register(new PhoneIntentActionProvider(implicitActivityStarter, R.layout.call_btn));
 * </pre>
 * <p/>
 * To add functionality to launch an explicit intent using data generated by an IntentActionProvider, add the following code in Application.onCreate():
 * <pre>
 * AndroidActivityStarter customActivityStarter = new AndroidActivityStarter(context, new ComponentName(context, CustomActivity.class));
 * ResultActionProvider.register(new CustomExplicitIntentActionProvider(customActivityStarter, R.layout.directions_btn));
 * </pre>
 */
public class AndroidActivityStarter
	implements
	IntentStarter {
	public interface OnMissingActivityListener {
		public void handleMissingIntent(Intent intent);
	}

	private final Context context;
	private OnMissingActivityListener listener;

	/**
	 * Create an activity starter which launches implicit intents.
	 */
	public AndroidActivityStarter(Context context) {
		this.context = context;
		this.listener = createDefaultListener(context);
	}

	private OnMissingActivityListener createDefaultListener(final Context context) {
		return new OnMissingActivityListener() {
			@Override
			public void handleMissingIntent(Intent intent) {
				if (context instanceof Application) {
					Toast.makeText(context, "No Activity to handle intent", Toast.LENGTH_SHORT).show();
				}
			}
		};
	}

	public void setOnMissingActivityListener(OnMissingActivityListener listener) {
		this.listener = listener;
	}

	@Override
	public void startIntent(Intent intent) {
		setRequiredFlagsForSingleInstanceActivity(intent);
		if (intent.resolveActivity(context.getPackageManager()) != null) {
			context.startActivity(intent);
		} else {
			if (listener != null) {
				listener.handleMissingIntent(intent);
			}
		}
	}

	private void setRequiredFlagsForSingleInstanceActivity(Intent intent) {
		if ((intent.getFlags() & Intent.FLAG_ACTIVITY_NEW_TASK) == 0) {
			intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
		}
	}
}
